### ISSUE TITLE
Question about images outside the domain of available pertained models

### ISSUE THREAD

**Issue by Baran-phys** [uoguelph-mlrg/instance_selection_for_gans#1]
Nice work. My dataset is entirely outside the domain of available pre-trained models such as inceptionV3 or ResNet. And within your paper, you mentioned that if the Embedding function is not aligned with the target domain, the instance selection is not effective. I wonder if I still instance selection could be applied to my problem?

**Comment by TDeVries** [comment]
Thank you! How far out of domain is the dataset? In our experience the classes or objects in the dataset don't need to line up exactly with the classes from the pre-trained model in order to get good results (of course it will likely help if they do). The ImageNet pre-trained embeddings seem to work quite well as generic image embeddings, so I expect that as long as the dataset isn't too crazy (like audio spectrograms or something like that), it should still work.

**Comment by Baran-phys** [comment]
Hmm, I think then it won't be possible for me. My images are sth like this:[
<img width="982" alt="Screenshot 2020-09-09 at 13 24 42" src="https://user-images.githubusercontent.com/15968370/97631964-18b2f380-1a32-11eb-8667-74124cbfd890.png">
](url)

**Comment by TDeVries** [comment]
Ah, you might be right. My guess is that instance selection works best when there is a single object in the images that it can focus on, but that doesn't seem to be the case here.
