### ISSUE TITLE
Is the code for creating the UMAP in the paper available?

### ISSUE THREAD

**Issue by sarmientoj24** [uoguelph-mlrg/instance_selection_for_gans#4]
It doesn't seem to be available in the repository. What tool did you use and can it be available?

**Comment by TDeVries** [comment]
I used the UMAP library (https://github.com/lmcinnes/umap) to project Inception embeddings of the images into 2D, and then standard python and matplotlib to map images to those 2D points. I've attached the jupyter notebook I used to create the plots so that you can get an idea of the functions used (it is in a zip because github doesn't allow notebook uploads). 

Hope that helps!

[umap_plots.zip](https://github.com/uoguelph-mlrg/instance_selection_for_gans/files/6795611/umap_plots.zip)

**Comment by sarmientoj24** [comment]
Got it. Thanks for this. Just one more question. It does look like it's only calculating 1000 embedding points, right? 
When I try increasing this, the manifold density (i.e. the number of icons in the UMAP is of the same number as the number of images before and after pruning)

**Comment by TDeVries** [comment]
The 1000 embedding points is so that UMAP has enough points to properly map the distribution, but they are not all used to create the plot so it shouldn't affect the number of icons shown. To change that you would either need to adjust the grid size (to show more/less images in each plot), or if you are trying to show that pruning reduces the coverage of the image manifold then you would need to adjust the retention ratio when performing instance selection.

**Comment by sarmientoj24** [comment]
The pruning on the manifold projection via UMAP is obvious when the 1000 embedding points but the amount of images in the projection manifold is the same before and after pruning when I increase it to, say 10K. Retention ratio is 50%

**Comment by TDeVries** [comment]
Are you running this on ImageNet, or a different dataset? For ImageNet I don't think it will work with any more than ~1300 images per class. Also are you pruning in the Inception feature embedding space, or the UMAP projection space?

This behaviour could make sense. If there are enough images it may be that a 50% reduction doesn't result in a visible change. I'm also wondering if having that many samples would affect the way the UMAP creates its projection, since it takes into account the distance to nearest neighbours. More data points would result in more close neighbours, so the results of the projection might look different. You might have to play with the n_neighbors and min_dist parameters in UMAP a bit.

**Comment by sarmientoj24** [comment]
I am using a different dataset (but it has a class on the ImageNet). 

I am pruning the ref_embeddings
```
keep_indices = get_indices_to_keep(ref_embeddings, density_measure='gmm')
```

I am usually using 20K to 30K samples

**Comment by TDeVries** [comment]
Okay, that should be fine then. Tuning the UMAP parameters may be the way to go to get it working with larger datasets.
